config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :skills
  get 'users/show'

  get 'users/index'

  get 'users/edit'

  resources :definition_translations
  resources :definition_groups
  resources :groups
  resources :definition_themes

  devise_for :users
  resources :users

  resources :exemples
  resources :illustrations
  resources :themes
  resources :definitions
  resources :words

  get "dico_fr" => "words#dico_fr"
  get "dico_li" => "words#dico_li"

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/team'
  get 'pages/terms'
  get 'admin' => "pages#admin"

  get 'admin_words' => 'pages#admin_words'
  get 'admin_definitions' => 'pages#admin_definitions'
  get 'admin_translations' => 'pages#admin_translations'
  get 'admin_definitions_themes' => 'pages#admin_definitions_themes'
  get 'admin_themes' => 'pages#admin_themes'
  get 'admin_definitions_groups' => 'pages#admin_definitions_groups'
  get 'admin_groups' => 'pages#admin_groups'
  get 'admin_searches' => 'pages#admin_searches'
  get 'export_words' => 'pages#export_words'
  get 'export_definiton' => 'pages#export_definition'
  get 'export_translation' => 'pages#export_translation'

  resources :words do
    collection do
      post :import
      post :import_updates
    end
  end

  resources :definitions do
    collection do
      post :import_updates
    end
  end

  resources :definition_translations do
    collection do
      post :import_updates
    end
  end
  root 'pages#home'

end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :definition_groups, dependent: :destroy
	has_many :definitions, through: :definition_groups

	belongs_to :contributor, :class_name => "User"

	def title
		if definitions.any?
			"#{definitions.last.word.name}..."
		end
	end

	def name
		if name_li.present?
			name_li
		end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        DefinitionGroup.create(:definition_id => @group.first_definition_id, :group_id => @group.id, :contributor_id => current_user.id)

        format.html { redirect_to :back, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }

        
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name_li, :name_fr, :contributor_id, :first_definition_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="row">
    <div class="col m8">
      
      <div class="">

      <%= f.text_field :name_li, label: false, placeholder: "Désignez l'élément commun au groupe de mots" %>
      </div>
    </div>
    <!--<div class="field">
      <%= f.label :name_fr %><br>
      <%= f.text_field :name_fr %>
    </div>-->
    <%= f.hidden_field :contributor_id, value: current_user.id %>
    <%= f.hidden_field :first_definition_id, value: definition.id %>
    <div class="col m4">
      <small><%= f.submit "Associer", class: "btn right" %></small>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h3>Modifiez le groupe de mot</h3>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="row">
    <div class="col m8">
      
      <div class="">

      <%= f.text_field :name_li, label: false, placeholder: "Modifiez l'élément commun au groupe de mots" %>
      </div>
    </div>
    <!--<div class="field">
      <%= f.label :name_fr %><br>
      <%= f.text_field :name_fr %>
    </div>-->
    <%= f.hidden_field :contributor_id, value: current_user.id %>
    
    <div class="col m4">
      <small><%= f.submit "Associer", class: "btn right" %></small>
    </div>
  </div>
<% end %>

<% if @group.definitions.count > 1 %>

<small><b>Pour rappel, ce groupe rassemble les mots suivants :</b>
<br><% @group.definitions.each do |definition| %>
        <i><%= link_to definition.name, word_path(definition.word) %>,</i>
    <% end %>
</small>

<% end %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name li</th>
      <th>Name fr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.title %></td>
        
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.title %>
  
</p>


<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>