config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :skills
  get 'users/show'

  get 'users/index'

  get 'users/edit'

  resources :definition_translations
  resources :definition_groups
  resources :groups
  resources :definition_themes

  devise_for :users
  resources :users

  resources :exemples
  resources :illustrations
  resources :themes
  resources :definitions
  resources :words

  get "dico_fr" => "words#dico_fr"
  get "dico_li" => "words#dico_li"

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/team'
  get 'pages/terms'
  get 'admin' => "pages#admin"

  get 'admin_words' => 'pages#admin_words'
  get 'admin_definitions' => 'pages#admin_definitions'
  get 'admin_translations' => 'pages#admin_translations'
  get 'admin_definitions_themes' => 'pages#admin_definitions_themes'
  get 'admin_themes' => 'pages#admin_themes'
  get 'admin_definitions_groups' => 'pages#admin_definitions_groups'
  get 'admin_groups' => 'pages#admin_groups'
  get 'admin_searches' => 'pages#admin_searches'
  get 'export_words' => 'pages#export_words'
  get 'export_definiton' => 'pages#export_definition'
  get 'export_translation' => 'pages#export_translation'

  resources :words do
    collection do
      post :import
      post :import_updates
    end
  end

  resources :definitions do
    collection do
      post :import_updates
    end
  end

  resources :definition_translations do
    collection do
      post :import_updates
    end
  end
  root 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :skills
    has_many :themes, through: :skills

    has_many :words, :foreign_key => "contributor_id"
    has_many :themes, :foreign_key => "contributor_id"
    has_many :groups, :foreign_key => "contributor_id"
    has_many :exemples, :foreign_key => "contributor_id"
    has_many :definitions, :foreign_key => "contributor_id"
    has_many :definition_translations, :foreign_key => "contributor_id"
    has_many :definition_themes, :foreign_key => "contributor_id"
    has_many :definition_groups, :foreign_key => "contributor_id"

    def full_name
      "#{first_name} #{last_name}"
    end

    def translations
      definition_translations
    end

    def name_or_placeholder
      if full_name.present?
        full_name
      else
        email.split("@")[0]
      end
    end

    def associations
      definition_groups
    end

    def contributions_count
      words.count + definitions.count + translations.count + themes.count + associations.count 
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all
  	
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = current_user

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :is_contributor, :is_admin)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_associations.html.erb
<li>
      <div class="collapsible-header">
      	<i class="material-icons">group_work</i>Associations de mots crées
      </div>

      <div class="collapsible-body">
      	<ul class="collection">

			<% @user.groups.sort_by{ |a| a.name or 0 }.each do |association| %>
				<li class="collection-item">

					<%= association.name if association.name %> <small>(<%= link_to "Modifier le nom de l'association", edit_group_path(association) %> | <%= link_to "Supprimer ce groupe de mots", association, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %>)</small>
					<br>
					<small>
						<b>Mots associés : </b>
						<% association.definitions.sort_by{ |a| a.name or 0 }.each do |definition| %>
        <i><%= link_to definition.name, word_path(definition.word) %>,</i>
    <% end %>

					</small>
				</li>
			<% end %>
		</ul>
	</div>
      	
</li>

<li>
      <div class="collapsible-header">
      	<i class="material-icons">group_work</i>Mots ajoutés à une association
      </div>

      <div class="collapsible-body">
      	<ul class="collection">
			
			<% @user.definition_groups.sort_by{ |a| a.name or 0 }.each do |associated| %> 
				<% if associated.definition %>

				<li class="collection-item">

					
					
					<%= associated.definition.content %> 
					<small>(<%= link_to "Changer d'association", edit_definition_group_path(associated) %> 
					| <%= link_to "Supprimer l'association de ce mot au groupe '#{associated.group.name if associated.group.name}'", associated, method: :delete, data: { confirm: 'Etes-vous sûr ?' } %>)
					</small>

					<small>
					<br>Mot ainsi défini : <%= link_to associated.definition.name, word_path(associated.definition.word) if associated.definition.name %>
					<br>Nom de l'association de mots :
						<b><%= associated.group.name if associated.group.name %></b>

					<br><b>Autres mots de la même association : </b>
						
			                <% associated.group.definitions.sort_by(&:name).each do |terme_associe| %>
			                  <% unless terme_associe == associated %>
			                    <%= link_to terme_associe.name, word_path(terme_associe.word) if terme_associe.name %>, 
			                  <% end %>
			                <% end %>
			            

					</small>

					
				</li>
				<% end %>
			<% end %>
		</ul>
	</div>  	
</li>

app/views/users/_definitions.html.erb
<li>
      <div class="collapsible-header">
      	<i class="material-icons">subject</i>Définitions ajoutées
      </div>
      <div class="collapsible-body">
      	
      	<ul class="collection">
				
			<% @user.definitions.sort_by(&:name).each do |definition| %>
				<li class="collection-item">
					<small>Définition de <%= link_to definition.word.name, word_path(definition.word) %></small>
          			<br><%= definition.content %> <small>(<%= link_to "voir", definition_path(definition)  %> | <%= link_to "modifier", edit_definition_path(definition) %>)</small>
				</li>
			<% end %>


			
		</ul>

      	



      </div>
</li>

app/views/users/_exemples.html.erb
    <li>
      <div class="collapsible-header">
      	<i class="material-icons">info_outline</i>Exemples ajoutés
      </div>

      <div class="collapsible-body">
      	<ul class="collection">

      	<% @user.exemples.sort_by(&:content).each do |exemple| %>
			<li class="collection-item">
				
          		
          		<%= exemple.content %>
          		<small>(<%= link_to "modifier l'exemple", edit_exemple_path(exemple) %>)
          		</small>
          		<br>
          		<small>Exemple attribué à la définition de <%= link_to exemple.definition.name, word_path(exemple.definition.word) %> suivante : "<i><%= exemple.definition.content %></i>"</small>
			</li>
		<% end %>
		</ul>

      	
      </div>
    </li>

app/views/users/_themes.html.erb
<li>
      <div class="collapsible-header">
        <i class="material-icons">label</i>Thèmes ajoutés au lexique
      </div>

      <div class="collapsible-body">

      	<ul class="collection">
				
			<% @user.themes.order("name ASC").each do |theme| %>
				<li class="collection-item">
					<%= theme.name %>
					<small>
						(<%= link_to "voir", theme_path(theme)  %> | <%= link_to "modifier", edit_theme_path(theme) %>)
					</small>
				</li>
			<% end %>
			
		</ul>

      </div>
</li>

<li>
      <div class="collapsible-header">
      	<i class="material-icons">label</i>Thèmes ajoutés aux définitions
      </div>



      <div class="collapsible-body">
      	<ul class="collection">

      	<% @user.definition_themes.order("created_at DESC").each do |theme| %>
			<li class="collection-item">
				
          		
          		<%= theme.name %>
          		<small>(<%= link_to "attribuer à un autre thème", edit_definition_theme_path(theme) %>)
          		</small>
          		<br>
          		<small>
                <% if theme.definition %>
                Thème attribué à la définition de <%= link_to theme.definition.name, word_path(theme.definition.word) %> suivante : "<i><%= theme.definition.content %></i>"
                <% end %>
                </small>
			</li>
		<% end %>
		</ul>
      	
      </div>
    </li>

app/views/users/_traductions.html.erb
<li>
      <div class="collapsible-header">
      	<i class="material-icons">language</i>Traductions ajoutées
      </div>

      <div class="collapsible-body">
      	<ul class="collection">
				
			<% @user.definition_translations.where.not(definition_id: nil).sort_by(&:name).each do |translation| %>
				
				<li class="collection-item">
					<small>Traduction de <%= link_to translation.word.name, word_path(translation.word) if translation.definition && translation.word %></small>
          			<br><%= translation.definition.word.name %>
          			(<%= link_to "modifier l'expression", edit_word_path(translation.definition.word) %> | <%= link_to "modifier la traduction", edit_definition_translation_path(translation) %>)</small>
				</li>
			<% end %>
			
		</ul>
      </div>
    </li>

app/views/users/_words.html.erb
<li>
      <div class="collapsible-header">
      	<i class="material-icons">library_books</i>Mots ajoutés au dictionnaire
      </div>
      
      <div class="collapsible-body">

      	<div class="row">
			<div class="col m6 s12">
			

			<ul class="collection">
				<li class="collection-item">
					En lingala
				</li>
			<% @user.words.in_lingala.order("name ASC").each do |word| %>
				<li class="collection-item">
				<%= link_to word.name, word_path(word) %> <small>(<%= link_to "modifier", edit_word_path(word) %>)</small>
				</li>
			<% end %>


			
			</ul>
			</div>

			<div class="col m6 s12">
			
			<ul class="collection">
				<li class="collection-item">
					En français
				</li>
			<% @user.words.in_french.order("name ASC").each do |word| %>
				<li class="collection-item">
				<%= link_to word.name, word_path(word) %>
				<small>(<%= link_to "modifier", edit_word_path(word) %>)</small>
				</li>
			<% end %>
			</ul>
			</div>
		</div>

      	
      		
      	
      </div>
    </li>

app/views/users/edit.html.erb
<h3>Modifiez votre profil</h3>
<hr>

<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

		<div class="row">
			<div class="col m4 s12">

				<%= f.text_field :first_name, :placeholder => "Prénom", class: "form-control" %>
			</div>
			<div class="col m4 s12">
				<%= f.text_field :last_name, :placeholder => "Nom", class: "form-control" %>
			</div>
		</div>



<%= f.submit "Mettre à jour le profil", class: 'btn btn-primary btn-block btn-lg' %>
		<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<% if user_signed_in? and current_user.first_name.blank? %>
<h3 class="center-align">
<br><br>
<%= link_to "Mettez à jour votre profil", edit_user_path(current_user) %></h3>

<% else %>

<h3>
	<%= @user.name_or_placeholder %>
	
	<small><small><small><small>
		
		<%= link_to "Mettre à jour", edit_user_path(current_user), class: "waves-effect waves-light btn right" %>
			
	</small></small></small></small>

</h3>

<% if @user.skills.any? %>
<hr>


	<h5>Domaines d'expertise :</h5>

	<% @user.skills.each do |skill| %>
		<%= skill.theme %>
		<% if skill.certified %>
			<small>par diplome (dernier diplôme : <%= skill.last_diploma %>)</small> 
		<% end %>

		<% if skill.practiced %>
		<small>par la pratique (dernier projet : <%= skill.last_project %>)</small> 
		<% end %>
	<% end %>
<% end %>


<% end %>

<hr>


<h5>Contributions :</h5>

 <ul class="collapsible" data-collapsible="accordion">
    <%= render "words" %>

    <%= render "definitions" %>

    <%= render "traductions" %>

    <%= render "themes" %>

    <%= render "exemples" %>

    <%= render "associations" %>

  </ul>


<script type="text/javascript">
	$(document).ready(function(){
    $('.collapsible').collapsible();
  });
</script>