config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :skills
  get 'users/show'

  get 'users/index'

  get 'users/edit'

  resources :definition_translations
  resources :definition_groups
  resources :groups
  resources :definition_themes

  devise_for :users
  resources :users

  resources :exemples
  resources :illustrations
  resources :themes
  resources :definitions
  resources :words

  get "dico_fr" => "words#dico_fr"
  get "dico_li" => "words#dico_li"

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/team'
  get 'pages/terms'
  get 'admin' => "pages#admin"

  get 'admin_words' => 'pages#admin_words'
  get 'admin_definitions' => 'pages#admin_definitions'
  get 'admin_translations' => 'pages#admin_translations'
  get 'admin_definitions_themes' => 'pages#admin_definitions_themes'
  get 'admin_themes' => 'pages#admin_themes'
  get 'admin_definitions_groups' => 'pages#admin_definitions_groups'
  get 'admin_groups' => 'pages#admin_groups'
  get 'admin_searches' => 'pages#admin_searches'
  get 'export_words' => 'pages#export_words'
  get 'export_definiton' => 'pages#export_definition'
  get 'export_translation' => 'pages#export_translation'

  resources :words do
    collection do
      post :import
      post :import_updates
    end
  end

  resources :definitions do
    collection do
      post :import_updates
    end
  end

  resources :definition_translations do
    collection do
      post :import_updates
    end
  end
  root 'pages#home'

end

app/models/word.rb
class Word < ActiveRecord::Base

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :definitions, dependent: :destroy
	has_many :definition_translations

	has_many :exemples, dependent: :destroy

	belongs_to :contributor, :class_name => "User"

	validates :name, presence: true

  scope :in_french, lambda {where(:is_fr => true)}
  scope :in_lingala, lambda {where(:is_li => true)}

	include PgSearch
	pg_search_scope :search_by_name, against: :name,
									ignoring: :accents,
                  using: {
                      trigram: {
                          threshold: 0.25
                      }
                  }, :ranked_by => ":trigram"

  def translations
  	self.definition_translations
  end

	def self.import_file file, contributor

		words = []
		definitions = []
		exemples = []

		spreadsheet = Roo::Spreadsheet.open(file.path)

		(2..spreadsheet.last_row).each do |i|
			row = spreadsheet.row(i)
			words << Word.new(contributor: contributor, name: row[0], prononciation: row[1], is_li: true, imported_file: file.path, imported_row: row)
		end

		Word.import(words)

		(2..spreadsheet.last_row).each do |i|
			row = spreadsheet.row(i)
			word = Word.find_by(name: row[0])
			# create the definitions in french
			if row[2] != nil
				definitions  << Definition.new(contributor: contributor, word: word, content: row[2], is_fr: true, imported_file: file.path, imported_row: row)
			end

			# create the definitions in english
			if row[3] != nil
				definitions << Definition.new(contributor: contributor, word: word, content: row[3], is_en: true, imported_file: file.path, imported_row: row)
			end

			# create exemples
			if row[4] != nil
				exemples << Exemple.new(contributor: contributor, word: word, content: row[4], is_li: true, imported_file: file.path, imported_row: row)
			end

			# create the definitions in ligala
			if row[5] != nil
				definitions << Definition.new( contributor: contributor, word: word, content: row[5], is_li: true, imported_file: file.path, imported_row: row)
			end
		end

		Exemple.import(exemples)
		Definition.import(definitions)

	end

	def self.import_updates file, contributor

    definitions = []
    exemples = []

		spreadsheet = Roo::Spreadsheet.open(file.path)

		(2..spreadsheet.last_row).each do |i|

			row = spreadsheet.row(i)
			word = Word.find(row[0])
			# create the definitions in french
			if row[1] == 1
				word.destroy
      else

        # modify words data
        word.update(name: row[2], prononciation: row[3])
        # create or modifying the definitions in french
        if word.definitions.where(is_fr: true).first
          word.definitions.where(is_fr: true).first.update(content: row[4])
        elsif row[4] != nil
          definitions << Definition.new(contributor: contributor, word: word, content: row[4], is_fr: true, imported_file: file.path, imported_row: row)
        end

        # create or modifying the definitions in english
        if word.definitions.where(is_en: true).first
          word.definitions.where(is_en: true).first.update(content: row[5])
        elsif row[5] != nil
          definitions << Definition.new(contributor: contributor, word: word, content: row[5], is_fr: true, imported_file: file.path, imported_row: row)
        end

        # create or modifying the exemples
        if word.exemples.first
          word.exemples.first.update(content: row[6])
        elsif row[6] != nil
          exemples << Exemple.new(contributor: contributor, word: word, content: row[6], is_li: true, imported_file: file.path, imported_row: row)
        end

        # create the definitions in ligala
        if word.definitions.where(is_li: true).first
          word.definitions.where(is_li: true).first.update(content: row[7])
        elsif row[7] != nil
          definitions << Definition.new(contributor: contributor, word: word, content: row[7], is_fr: true, imported_file: file.path, imported_row: row)
        end

      end
		end

    Exemple.import(exemples)
    Definition.import(definitions)

	end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]



  # GET /words
  # GET /words.json
  def index
    #@words, @alphaParams = Word.in_lingala.order('name ASC').alpha_paginate(params[:letter]){|word| word.name}
    @words = Word.in_lingala.order('name ASC').where.not(name: [nil, '']).page(params[:page])
  end

  def dico_fr
    @words = Word.in_french.order('name ASC').where.not(name: [nil, '']).page(params[:page])
  end

  def dico_li
    @words = Word.in_lingala.order('name ASC')
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @definition = @word.definitions.new
    @definition_theme = DefinitionTheme.new
    @themes = Theme.all
    @exemple = Exemple.new
    @groups = Group.all
    @definition_group = DefinitionGroup.new
    @words = Word.all
    @definition_translation = DefinitionTranslation.new
    @group = Group.new
    @search = Search.new
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    if current_user.is_admin
      Word.import_file(params[:file], current_user)
      redirect_to admin_words_path, notice: 'Les mots on bien ete importé.'
    else
      redirect_back fallback_location: root_path, notice: "Vous n'etes pas autorisez a faire cette action"
    end
  end

  def import_updates
    if current_user.is_admin
      Word.import_updates(params[:file], current_user)
      redirect_to admin_words_path, notice: 'Les mots on bien ete modifié.'
    else
      redirect_back fallback_location: root_path, notice: "Vous n'etes pas autorisez a faire cette action"
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:name, :is_fr, :is_li,
                                  :prononciation, :root, :structure, :role,
                                  :contributor_id, :source, :is_validated,
                                  :image, :image_title, :image_description, :image_url)
    end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="col m3 s12">
      <div class="input-field">
        <%= f.text_field :name, label: false, placeholder: "Nom" %>
      </div>
    </div>

    <div class="col m3 s12">
      <div class="input-field"> 
        <%= f.text_field :prononciation, label: false, placeholder: "Prononciation" %>
      </div>
    </div>

      <div class="col m2 s4">
        <div class="input-field">
          <%= f.label :is_fr, "français" %>
          <%= f.check_box :is_fr %>
        </div>
      </div>

      <div class="col m2 s4">
        <div class="input-field">
          <%= f.label :is_li, "lingala" %>
          <%= f.check_box :is_li %>
        </div>
      </div>

      <div class="col m2 s4">
        <div class="input-field">
          <%= f.label :is_en, "english" %>
          <%= f.check_box :is_en %>
        </div>
      </div>

    </div>

    <div class="row">

      <div class="col m4 s12">
        <div class="input-field"> 
          <%= f.text_field :root, label: false, placeholder: "Racine" %>
        </div>
      </div>

      <div class="col m4 s12">
        <div class="input-field"> 
          <%= f.text_field :structure, label: false, placeholder: "Structure" %>
        </div>
      </div>

      <div class="col m4 s12">
        <div class="input-field"> 
          <%= f.text_field :role, label: false, placeholder: "Partie du discours" %>
        </div>
      </div>
    </div>

    <!--<div class="col m12 s12">
      <div class="input-field"> 
        <%= f.text_field :source, label: false, placeholder: "Source" %>
      </div>
    </div>
  </div>-->

<div class="card">
<div class="card-content">
<h5><small><u>Admin : modifier l'illustration</u></small></h5>
  <%= f.file_field :image %>
  <%= f.text_field :image_title, label: false, placeholder: "Titre de l'illustration" %>
  <%= f.text_area :image_description, label: false, placeholder: "Description de l'illustration" %>
  <%= f.text_field :image_url, label: false, placeholder: "Lien externe" %>
  </div>
  </div>
  <div class="row">

    
<!--
    <div class="col m2 s4">
      <div class="input-field">
        <%= f.check_box :is_validated %>
        <%= f.label :is_validated, "validé" %>
      </div>
    </div>
  -->

    <%= f.hidden_field :contributor_id, value: current_user.id %>
    <div class="center-align">
        <%= f.submit "Ajouter ce mot au dictionnaire", class: "waves-effect waves-light btn-large" %>
    </div>
  </div>
 


<% end %>

app/views/words/_form_image.html.erb
<%= form_for @word, html: { multipart: true } do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.file_field :image %>
  <%= f.text_field :image_title, label: false, placeholder: "Titre de l'illustration" %>
  <%= f.text_area :image_description, label: false, placeholder: "Description de l'illustration" %>
  <%= f.text_field :image_url, label: false, placeholder: "Lien externe" %>

  <div class="center-align">
        <%= f.submit "Ajouter cette illustration", class: "waves-effect waves-light btn right" %>
    </div>

<% end %>

app/views/words/_right_pane.html.erb
<% if @word.image.present? %>


<div class="card">


<%= link_to @word.image_url, target: "_blank" do %>
	<div class="card-image">
        <!--<img src="http://lorempixel.com/100/90/nature/6"> -->
        <%= image_tag @word.image.url(:medium) %>
        <span class="card-title">
        	<%= @word.image_title %>

        	
        </span>
        
    </div>
<% end %>
            
    <div class="card-content">
        <p><%= @word.image_description %></p>
    </div>

<div class="card-action">
    <%= link_to edit_word_path(@word) do %>
        		<i class="material-icons">edit</i> modifier l'illustration
        	<% end %>
</div>
            <!--<div class="card-action">
              <a href="#">This is a link</a>
            </div>-->
</div>

<% else %>

	
<div class="card">
	<div class="card-image">
        <img src="http://lorempixel.com/100/90/nature/6"> 
        <!--<%= image_tag @word.image.url(:medium) %>-->
        <span class="card-title">
        <button data-target="modal_image" class="btn modal-trigger right">
        	<i class="material-icons">add</i> 
        </button>
        </span>
    </div>
            
    
</div>
		

	

<% end %>
    

app/views/words/_word_fr.html.erb
<ul class="collection">


<% @word.translations.each do |translation| %>


<li class="collection-item">
	<h5>
		<%= link_to translation.name, word_path(translation.definition.word) %>

    <small>

        (<i>
        <%= translation.definition.word.prononciation if translation.definition.word.prononciation %>

        </i>)

        <% if translation.definition.themes.any? %>
          <span class="new badge teal" data-badge-caption="">
            <%= link_to translation.definition.definition_themes.last.name, theme_path(translation.definition.definition_themes.last.theme) %>
          </span>
          <br>
        <% end %>
      </small>
	</h5>


	<p><%= simple_format(translation.definition.content) %></p>

<!-- associations -->

<% if translation.definition.groups.any? %>
    <p>
              <small><strong>Voir aussi : </strong></small>
              <br>
              <% translation.definition.groups.each do |group| %>
                <% group.definitions.each do |terme_associe| %>
                  <% unless terme_associe == translation.definition %>
                    <%= link_to terme_associe.name, word_path(terme_associe.word) %>
                  <% end %>
                <% end %>
              <% end %>
            </p>
<% end %>



	</li>
<% end %>
</ul>

app/views/words/_word_li.html.erb
<ul class="collection">


<!-- definitions visible to all -->

  <% @word.definitions.each do |definition| %>



    <!-- contenu de la définition -->

      <li class="collection-item">

        <% if definition.themes.any? %>

                <span class="new badge teal" data-badge-caption="">
                  <%= link_to definition.definition_themes.last.name, theme_path(definition.definition_themes.last.theme) %>
                </span>
                <br>

        <% end %>

        <%= simple_format(definition.content) || "" %>

        <% if current_user %>
          <% if current_user.id == definition.contributor_id %>
            <%= link_to edit_definition_path(definition) do %>
              <i class="tiny material-icons">edit</i>
            <% end %>
              <button data-target="modal5_<%= definition.id %>" class="btn-floating red modal-trigger"><i class="material-icons">language</i></button>

              <a data-target="modal3_<%= definition.id %>" class="btn-floating yellow darken-1 modal-trigger"><i class="material-icons">info_outline</i></a>

              <button data-target="modal2_<%= definition.id %>" class="btn-floating green modal-trigger"><i class="material-icons">label</i></button>

              <a data-target="modal4_<%= definition.id %>" class="btn-floating blue modal-trigger"><i class="material-icons">group_work</i></a>

          <% end %>
        <% end %>


    <!-- traductions -->

        <% if definition.definition_translations.any? %>
        <p>
          <small><strong>En français : </strong></small>
          <br>

          <% definition.definition_translations.each do |translation| %>
              <% if translation.word %>
                <%= link_to translation.word.name, word_path(translation.word) %>


                <% if current_user %>
                  <% if current_user.id == translation.word.contributor_id or current_user.is_admin %>
                     <!-- modifier le mot -->
                    <%= link_to edit_word_path(translation.definition.word) do %>
                      <%= content_tag(:i, "edit" ,:class=> 'tiny material-icons') -%>
                    <% end %>
                  <% end %>
                <% end %>

                <% if current_user %>
                  <% if current_user.id == translation.contributor_id or current_user.is_admin %>
                    <!-- associer à un autre mot -->
                    <%= link_to edit_definition_translation_path(translation) do %>
                      <%= content_tag(:i, "swap_horiz" ,:class=> 'tiny material-icons') -%>
                    <% end %>

                <% end %>
                <% end %>

              <% end %>
                <br>

          <% end %>

        </p>
        <% end %>
      <!-- associations -->

        <% if definition.groups.any? %>

            <p>
              <small><strong>Voir aussi : </strong></small>
              <br>

              <% definition.groups.each do |group| %>
                <small><b><%= group.name %>

                <!-- si le user a créé le groupe de mots -->
                <% if current_user %>
                    <% if current_user.id == group.contributor_id %>
                      <%= link_to edit_group_path(group) do %>
                        <%= content_tag(:i, "edit" ,:class=> 'tiny material-icons') -%>
                      <% end %>

                      <%= link_to group, method: :delete, data: { confirm: 'Etes-vous sûr ?' } do %>
                        <%= content_tag(:i, "delete", :class=> 'tiny material-icons') %>
                      <% end %>

                    <% end %>
                <% end %>

                :</b></small>


                <% group.definitions.sort_by(&:name).each do |terme_associe| %>

                  <% unless terme_associe == definition %>
                    <%= link_to terme_associe.name, word_path(terme_associe.word) if terme_associe.word %>

                    <!-- si le user a créé la définition objet de l'association -->
                    <% if current_user %>
                      <% if current_user.id == terme_associe.contributor_id %>

                        <%= link_to edit_definition_path(terme_associe) do %>
                          <%= content_tag(:i, "edit" ,:class=> 'tiny material-icons') -%>
                        <% end %>

                      <% end %>
                    <% end %>

                    <!-- si le user est l'auteur de l'association-même, alors il peut modifier cette association ou la supprimer -->
                    <% terme_associe.definition_groups.each do |association| %>
                      <% if current_user %>
                        <% if current_user.id == association.contributor_id %>

                          <%= link_to edit_definition_group_path(association) do %>
                            <%= content_tag(:i, "swap_horiz" ,:class=> 'tiny material-icons') -%>
                          <% end %>

                          <%= link_to association, method: :delete, data: { confirm: 'Etes-vous sûr ?' } do %>
                            <%= content_tag(:i, "delete" ,:class=> 'tiny material-icons') -%>
                          <% end %>

                        <% end %>
                      <% end %>
                    <% end %>

                    ,
                  <% end %>

                <% end %><br>


              <% end %>
            </p>

        <% end %>




    <!-- visible only when signed in -->



          <% if current_user %>
          <!-- Modal Structure Groupe -->
            <div id="modal4_<%= definition.id %>" class="modal bottom-sheet">
              <div class="modal-content container">
                <h6>Associez cette définition à d'autres termes,
                 ou rendez-vous en bas de la liste pour créer une nouvelle association
                </h6>



                <ul class="collection">
                  <% @groups.sort_by(&:name_li).each do |group| %>
                    <li class="collection-item">
                      <div class="row">
                        <div class="col m9">
                          <b><%= group.name_li %> :</b>
                          <% group.definitions.sort_by(&:name).each do |definition| %>
                            <i><%= definition.name %>,</i>
                          <% end %>
                        </div>
                        <div class="col m3">
                        <%= render partial: "definition_groups/form", locals: {definition: definition, group: group} %>
                        </div>
                      </div>
                     </li>


                  <% end %>
                  <li class="collection-item">
                      <div class="row">
                        <div class="col m4">
                          Aucune association ne convient ? Créez-en une nouvelle :
                        </div>
                        <div class="col m8">
                        <%= render partial: "groups/form", locals: {definition: definition} %>
                        </div>
                      </div>
                     </li>
                </ul>


              </div>
            </div>
        <br>

          <!-- Modal Structure Theme -->
          <div id="modal2_<%= definition.id %>" class="modal bottom-sheet">
            <div class="modal-content container">
              <h6>Ajoutez un thème à cette définition de <%= @word.name %></h6>
              <hr>
              <div class="row">

                  <div class="col m9 s12">
                    <%= render partial: "definition_themes/form", locals: {definition: definition} %>

                  </div>
                  <div class="col m3 s12">
                    <%= link_to "ou ajoutez un nouveau thème au lexique", new_theme_path %>
                  </div>

              </div>
            </div>
              <!--<div class="modal-footer">
                <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
              </div>-->
          </div>

        <!-- Modal Structure Translate -->
        <div id="modal5_<%= definition.id %>" class="modal bottom-sheet">
          <div class="modal-content container">
            <h6>Ajoutez une traduction à cette définition de <%= @word.name %></h6>
            <div class="row">

              <div class="col m9 s12">
              <%= render partial: "definition_translations/form", locals: {definition: definition} %>
              </div>

              <div class="col m3 s12">
              <%= link_to "ou ajoutez un nouveau mot au dictionnaire", new_word_path %>
              </div>

            </div>
          </div>
            <!--<div class="modal-footer">
              <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
            </div>-->
        </div>

          <% end %>




        <% end %>
      </ul>

app/views/words/dico_fr.html.erb
<h3 class="center-align">Dictionnaire français - lingala <br><small><small><%= link_to "Voir le dictionnaire lingala - français", dico_li_path, class: "text-muted" %></small></small></h3>
<div class="divider"></div>

 <div class="collection">
    <% @words.each do |word| %>
      <div class="collection-item">
      <h5><%= link_to word.name.titleize, word_path(word) %>
        
        
      </h5>
      <% if word.translations.any? %>
      <p><% word.translations.each do |translation| %>
      <%= translation.definition.word.name if translation && translation.definition %>, 
      <% end %>
      </p>
      <% end %>
      
    </div>
    <% end %>
</div>

<div class="center-align"><small><%= paginate @words %> </small></div>

<br>

<a class="btn-floating btn-large waves-effect waves-light right" href="/words/new"><i class="material-icons">edit</i></a>

app/views/words/dico_li.html.erb
<h3 class="center-align">
Dictionnaire lingala - français
<br><small><small><%= link_to "Voir le dictionnaire français - lingala", dico_fr_path, class: "text-muted" %></small></small>
</h3>
<div class="divider"></div>

 <div class="collection">
    <% @words.each do |word| %>
      <div class="collection-item">
      <h5><%= link_to word.name.titleize, word_path(word) %> <small>(<i><%= word.prononciation if word.prononciation %></i>)</small>
        <!--<span class="badge">
          <% if word.is_fr %>français<% end %>
          <% if word.is_li %>lingala<% end %>
        </span> -->
        
      </h5>
      <p>
        
        <% if word.definitions.any? && word.definitions.last.definition_translations %>
          <% word.definitions.last.definition_translations.each do |translation| %>
            <%= translation.word.name if translation && translation.word %>, 
          <% end %>
        
        <% end %>
      </p>
      

       
        <!--<td><%= word.contributor_id %></td>
        <td><%= word.source %></td>
        <td><%= word.is_validated %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      
    </div>
    <% end %>
</div>

<div class="center-align"><small><%= paginate @words %> </small></div>

<br>

<!--<%= link_to 'New Word', new_word_path %> -->

<a class="btn-floating btn-large waves-effect waves-light right" href="/words/new"><i class="material-icons">edit</i></a>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<h3 class="center-align">
Dictionnaire lingala




</h3>


<div class="divider"></div>

<div id="pagination_table">
 <div class="collection">
    <% @words.each do |word| %>
      <div class="collection-item">
      <h5><%= link_to word.name.titleize, word_path(word) %> <small>(<i><%= word.prononciation if word.prononciation %></i>)</small>
        <span class="badge">
          <% if word.is_fr %>français<% end %>
          <% if word.is_li %>lingala<% end %>
        </span>
        <span class="new badge purple" data-badge-caption="définitions"><%= word.definitions.count %></span>
      </h5>
      <p><%= word.definitions.last.content if word.definitions.any? %></p>

       
        <!--<td><%= word.contributor_id %></td>
        <td><%= word.source %></td>
        <td><%= word.is_validated %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      
    </div>
    <% end %>
</div>

<div class="center-align"><small><%= paginate @words %> </small></div>
</div>

<br>

<!--<%= link_to 'New Word', new_word_path %> -->

<a class="btn-floating btn-large waves-effect waves-light right" href="/words/new"><i class="material-icons">edit</i></a>

app/views/words/new.html.erb
<h4 class="center-align">Ajouter un nouveau mot</h4>
<div class="divider"></div>

<%= render 'form' %>

<!--<%= link_to 'Back', words_path %>-->

app/views/words/show.html.erb
  <h3>
    <%= @word.name.titleize %>
      <% if current_user %>
        <% if current_user.id == @word.contributor_id || current_user.is_admin %>
          <%= link_to edit_word_path(@word) do %>
            <%= content_tag(:i, "edit" ,:class=> 'small material-icons') -%>
          <% end %>
        <% end %>
      <% end %>

    <% if @word.is_li %>
    <small>
      (<i><%= @word.prononciation if @word.prononciation %></i>)

      <% if current_user %>
      <button data-target="modal1" class="btn modal-trigger right"><i class="material-icons">edit</i></button>
      <% end %>
    </small>
    <br>
    <% end %>

  </h3>

  <% if @word.is_li %>
    <strong>racine :</strong> -<i><%= @word.root %></i>- <strong>| structure :</strong> <i><%= @word.structure %></i> <strong>| partie du discours :</strong> <i><%= @word.role %></i>
    <br>

    <% if @word.exemples.any? %>
    <p>
      <strong>exemple:</strong><br>
      <% @word.exemples.each do |exemple| %>
        - <%= exemple.content %>

        <% if user_signed_in? && current_user.id == exemple.contributor_id %>
          <%= link_to edit_exemple_path(exemple) do %>
            <%= content_tag(:i, "edit" ,:class=> 'tiny material-icons') -%>
          <% end %>

        <% end %>

        <br>
      <% end %>
    </p>

    <% end %>



    <% if current_user %>
        <!-- Modal Structure Exemple -->
        <div id="modal3_<%= @id %>" class="modal bottom-sheet">
          <div class="modal-content container">
            <%= render partial: "exemples/form", locals: {word: @word} %>
          </div>
        </div>
    <% end %>
  <% end %>

  <div class="divider"></div>

  <div class="row">

    <div class="col m8 s12">
    <% if @word.is_li %>
      <%= render "word_li" %>
    <% elsif @word.is_fr %>
      <%= render "word_fr" %>
    <% end %>


    </div>

    <div class="col m4 s12">

          <%= render "right_pane" %>



    </div>

</div>



  <!-- Modal Structure -->
  <div id="modal1" class="modal bottom-sheet">
    <div class="modal-content">

      <%= render "definitions/form" %>
    </div>
</div>

<!-- Modal Image -->
  <div id="modal_image" class="modal bottom-sheet">
    <div class="modal-content">

      <%= render "words/form_image" %>
    </div>
</div>

<hr>
<h5>Rechecher un autre mot</h5>
<%= render template: "searches/new" %>

<script type="text/javascript">
  $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal-trigger').leanModal();
  });
</script>