config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :skills
  get 'users/show'

  get 'users/index'

  get 'users/edit'

  resources :definition_translations
  resources :definition_groups
  resources :groups
  resources :definition_themes

  devise_for :users
  resources :users

  resources :exemples
  resources :illustrations
  resources :themes
  resources :definitions
  resources :words

  get "dico_fr" => "words#dico_fr"
  get "dico_li" => "words#dico_li"

  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/team'
  get 'pages/terms'
  get 'admin' => "pages#admin"

  get 'admin_words' => 'pages#admin_words'
  get 'admin_definitions' => 'pages#admin_definitions'
  get 'admin_translations' => 'pages#admin_translations'
  get 'admin_definitions_themes' => 'pages#admin_definitions_themes'
  get 'admin_themes' => 'pages#admin_themes'
  get 'admin_definitions_groups' => 'pages#admin_definitions_groups'
  get 'admin_groups' => 'pages#admin_groups'
  get 'admin_searches' => 'pages#admin_searches'
  get 'export_words' => 'pages#export_words'
  get 'export_definiton' => 'pages#export_definition'
  get 'export_translation' => 'pages#export_translation'

  resources :words do
    collection do
      post :import
      post :import_updates
    end
  end

  resources :definitions do
    collection do
      post :import_updates
    end
  end

  resources :definition_translations do
    collection do
      post :import_updates
    end
  end
  root 'pages#home'

end

app/models/definition_translation.rb
class DefinitionTranslation < ActiveRecord::Base
	belongs_to :definition 
	belongs_to :word
	belongs_to :contributor, class_name: "User"

  validates :definition, uniqueness: { scope: :word }

	scope :by_words, -> { includes(:word).order('words.name') }

	def name
		definition.name
	end

	def self.import_updates file, contributor
		# the goal of those array is to able to create words
		# and multiple many to manny relations
		# between eache of word and their corresponding defintions
		translated_ids = []
		translations = []
		word = []
		definitions_translation = []

		spreadsheet = Roo::Spreadsheet.open(file.path)

		(2..spreadsheet.last_row).each do |i|

			row = spreadsheet.row(i)
			def_trans = nil

			if row[0]
				def_trans = DefinitionTranslation.find(row[0])
				if row[1] == 1
					def_trans.destroy
				end
				# create a new definiton_translation
			elsif row[2] && row[4]
				if DefinitionTranslation.find_by(word_id: row[2], defintion_id: row[6]) == nil
					definitions_translation << DefinitionTranslation.new(word_id: row[2], defintion_id: row[6])
				end
			end

			if row[2] == nil && row[3] && row[6]

				translated_ids << row[6]

				if spreadsheet.row((i-1))[3] != row[3]
					translations << Word.new(name: row[3], is_fr: row[4], is_en: row[5])
					word << Word.new(name: row[3], is_fr: row[4], is_en: row[5], contributor: contributor)
				elsif spreadsheet.row((i-1))[3] == row[3]
					translations << Word.new(name: row[3], is_fr: row[4], is_en: row[5])
				end

			end

		end

		Word.import(word)

		translated_ids.each do |_id|
			# When a new translation must be created
			# I add the created translation and the cooresponding definition
			# in two different array at the same time
			# because of that they have the same index
			# So I can call the definition from the index of translation
			# and vise versa... Tada! Magic is done
			translated = Definition.find(_id)
			found_translation = translations[translated_ids.index(_id)]
			translation = Word.find_by(name: found_translation.name)
			unless DefinitionTranslation.where(definition: translated, word: translation).any?
				definitions_translation << DefinitionTranslation.new(definition: translated, word: translation)
			end
		end

		DefinitionTranslation.import(definitions_translation)

	end
end

app/controllers/definition_translations_controller.rb
class DefinitionTranslationsController < ApplicationController
  before_action :set_definition_translation, only: [:show, :edit, :update, :destroy]

  # GET /definition_translations
  # GET /definition_translations.json
  def index
    @definition_translations = DefinitionTranslation.all
  end

  # GET /definition_translations/1
  # GET /definition_translations/1.json
  def show
  end

  # GET /definition_translations/new
  def new
    @definition_translation = DefinitionTranslation.new
  end

  # GET /definition_translations/1/edit
  def edit
  end

  # POST /definition_translations
  # POST /definition_translations.json
  def create
    @definition_translation = DefinitionTranslation.new(definition_translation_params)

    respond_to do |format|
      if @definition_translation.save
        format.html { redirect_to :back, notice: 'Definition translation was successfully created.' }
        format.json { render :show, status: :created, location: @definition_translation }
      else
        format.html { render :new }
        format.json { render json: @definition_translation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definition_translations/1
  # PATCH/PUT /definition_translations/1.json
  def update
    respond_to do |format|
      if @definition_translation.update(definition_translation_params)
        format.html { redirect_to @definition_translation, notice: 'Definition translation was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition_translation }
      else
        format.html { render :edit }
        format.json { render json: @definition_translation.errors, status: :unprocessable_entity }
      end
    end
  end

  def import_updates
    if current_user.is_admin
      DefinitionTranslation.import_updates(params[:file], current_user)
      redirect_to '/definition_translations', notice: 'Les definiontion on bien été importé on bien ete modifié.'
    else
      redirect_back fallback_location: root_path, notice: "Vous n'etes pas autorisez a faire cette action"
    end
  end

  # DELETE /definition_translations/1
  # DELETE /definition_translations/1.json
  def destroy
    @definition_translation.destroy
    respond_to do |format|
      format.html { redirect_to definition_translations_url, notice: 'Definition translation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_definition_translation
      @definition_translation = DefinitionTranslation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def definition_translation_params
      params.require(:definition_translation).permit(:definition_id, :word_id,
                                                      :contributor_id)
    end
end

app/helpers/definition_translations_helper.rb
module DefinitionTranslationsHelper
end

app/views/definition_translations/_form.html.erb
<%= form_for(@definition_translation) do |f| %>
  <% if @definition_translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition_translation.errors.count, "error") %> prohibited this definition_translation from being saved:</h2>

      <ul>
      <% @definition_translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    
    <%= f.hidden_field :definition_id, value: definition.id %>
    <%= f.hidden_field :contributor_id, value: current_user.id %>
  
  <div class="col m3 s6">
   
    
    <%= f.collection_select :word_id, @words.in_french.order("name ASC"), :id, :name, {prompt: 'Choisissez parmi les mots existants'}, {class: "browser-default"} %>
  </div>


  <div class="col m3 s6">
  
    <%= f.submit "Confirmer", class: "btn" %>
  
  </div>
  </div>
<% end %>

app/views/definition_translations/edit.html.erb
<h4 class="center-align">Modifier la traduction française de <%= link_to @definition_translation.definition.name, word_path(@definition_translation.definition.word) %></h4>
<hr>



<%= form_for(@definition_translation) do |f| %>
  <% if @definition_translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition_translation.errors.count, "error") %> prohibited this definition_translation from being saved:</h2>

      <ul>
      <% @definition_translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row center-align">

  
  
   <div class="col m8 s12 offset-m2">
    <h6>Sélectionnez dans la liste un mot français qui correspond à <%= link_to @definition_translation.definition.name, word_path(@definition_translation.definition.word) %></h6>
    <%= f.collection_select :word_id, Word.in_french.order("name ASC"), :id, :name, {prompt: 'Choisissez parmi les mots existants'}, {class: "browser-default"} %>

    <br><%= f.submit "Confirmer la nouvelle traduction", class: "btn" %>
    <br><small>Le mot français n'est pas dans la liste ? <%= link_to "Ajoutez un nouveau mot français au dictionnaire", new_word_path %></small>
  </div>


 
  </div>
<% end %>

app/views/definition_translations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Definition Translations</h1>

<table>
  <thead>
    <tr>
      <th>Definition</th>
      <th>Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @definition_translations.each do |definition_translation| %>
      <tr>
        <td><%= definition_translation.definition_id %></td>
        <td><%= definition_translation.word_id %></td>
        <td><%= link_to 'Show', definition_translation %></td>
        <td><%= link_to 'Edit', edit_definition_translation_path(definition_translation) %></td>
        <td><%= link_to 'Destroy', definition_translation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Definition translation', new_definition_translation_path %>

app/views/definition_translations/new.html.erb
<h1>New Definition Translation</h1>

<%= render 'form' %>

<%= link_to 'Back', definition_translations_path %>

app/views/definition_translations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Definition:</strong>
  <%= @definition_translation.definition_id %>
</p>

<p>
  <strong>Word:</strong>
  <%= @definition_translation.word_id %>
</p>

<%= link_to 'Edit', edit_definition_translation_path(@definition_translation) %> |
<%= link_to 'Back', definition_translations_path %>